# Project: Queue_MO
# Makefile created by Dev-C++ 5.8.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ch6_QArray1.o TStoixeioyOuras.o TestQueue.o
LINKOBJ  = ch6_QArray1.o TStoixeioyOuras.o TestQueue.o
LIBS     = -L"C:/Program Files/Dev-Cpp/MinGW64/lib32" -L"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Program Files/Dev-Cpp/MinGW64/include" -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Program Files/Dev-Cpp/MinGW64/include" -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Queue_MO.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ch6_QArray1.o: ch6_QArray1.c
	$(CC) -c ch6_QArray1.c -o ch6_QArray1.o $(CFLAGS)

TStoixeioyOuras.o: TStoixeioyOuras.c
	$(CC) -c TStoixeioyOuras.c -o TStoixeioyOuras.o $(CFLAGS)

TestQueue.o: TestQueue.c
	$(CC) -c TestQueue.c -o TestQueue.o $(CFLAGS)
